package parquet

class FloorsNumberCanNotBeLessEqualZero extends Exception
class LengthCanNotBeLessEqualZero extends Exception
class WidthCanNotBeLessEqualZero extends Exception
class HeightCanNotBeLessEqualZero extends Exception
